name: Basic build and test

env:
  MANDREL_VERSION: "22.3.0.1-Final"
  NATIVE_JAVA_VERSION: "17"

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'datastaxdevs/quarkus-astra-intro-demo'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
    name: "jvm-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-java-${{ matrix.java }}"
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }}

  native-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'datastaxdevs/quarkus-astra-intro-demo'
    steps:
      - uses: actions/checkout@v3

      - name: Cache and restore Mandrel distro
        id: check-mandrel-cache
        uses: actions/cache@v3
        with:
          path: mandrel-${{ env.MANDREL_VERSION }}-${{ env.NATIVE_JAVA_VERSION }}.tar.gz
          key: mandrel-distro-${{ env.MANDREL_VERSION }}-${{ env.NATIVE_JAVA_VERSION }}

      - name: Download Mandrel
        if: steps.check-mandrel-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${MANDREL_VERSION}/mandrel-java${{ env.NATIVE_JAVA_VERSION }}-linux-amd64-${MANDREL_VERSION}.tar.gz"
          wget -q -O mandrel-${{ env.MANDREL_VERSION }}-${{ env.NATIVE_JAVA_VERSION }}.tar.gz $download_url

      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: mandrel-${{ env.MANDREL_VERSION }}-${{ env.NATIVE_JAVA_VERSION }}.tar.gz
          java-version: ${{ env.NATIVE_JAVA_VERSION }}
          architecture: x64
          cache: maven

      - name: "build-test-native"
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ env.NATIVE_JAVA_VERSION }}
